# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_role:
    name: tosit.tdp_extra.kafka.common
    tasks_from: install

- name: Create configuration directory
  file:
    path: "{{ kafka_client_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: "755"
